import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FileContextProvider } from '@/contexts/fileContext'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Audio Cutter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FileContextProvider>
          {children}
        </FileContextProvider>
      </body>
    </html>
  );
}
